/**
 * Generated by @openapi-codegen
 *
 * @version 10.9.1
 */
export type NotFoundError = {
  error?: {
    /**
     * @format int64
     */
    code?: number;
    message?: string;
  };
};

export type UnauthorizedError = {
  error?: {
    /**
     * @format int64
     */
    code?: number;
    message?: string;
  };
};
