/**
 * Generated by @openapi-codegen
 *
 * @version 10.9.1
 */
export type Id = number;

/**
 * @example 8cbb43fe-4cdf-4991-8352-c461779cec02
 */
export type UUId = string;

export type Collection = string;

export type Search = string;

export type Page = number;

export type Offset = number;

export type Sort = string[];

export type Meta = string;

export type Limit = number;

export type Filter = string[];

export type Fields = string[];

export type Mode = "jwt" | "cookie";

export type Export = "csv" | "json" | "xml" | "yaml";

export type Version = string;
